// Ward Mastery — Elaboration of Symptoms Data
// All symptom elaboration questions from ABM Abdullah Long Cases
// Referenced by app.js via questionsData

const SYMP_ELABORATION_DATA = {
    "elaboration_symptoms": {
        label: "🔬 Elaboration of Symptoms",
        subtypes: {
            "Fever": {
                icon: "🌡️",
                questions: [
                    "How long have you been suffering from fever?",
                    "When does it start (morning, evening, night)? How long does it persist (few hours or throughout the day)?",
                    "Is there any evening rise of temperature associated with night sweats?",
                    "What was the highest recorded temperature?",
                    "Is it associated with chills and rigors? Does it subside with sweating?",
                    "Does it subside spontaneously or with antipyretic?",
                    "Is the fever punctuated by apyrexial period? (Undulant / Pel-Ebstein)",
                    "Is the fever associated with skin rash or purpura?",
                    "Any associated symptoms? (urinary complaint, cough, chest pain, abdominal pain, headache, loss of consciousness, weight loss, polyarthritis)",
                    "Any history of sexual exposure, homosexuality, travel abroad?",
                    "Are you taking any drugs? (drug fever)"
                ],
                causes: [
                    "Low grade fever with evening rise → Tuberculosis",
                    "Fever with chill and rigor → Acute pyelonephritis, acute cholangitis, SBE, subphrenic abscess, pyogenic lung abscess, septicemia, lobar pneumonia, pyrogenic reaction",
                    "Fever with chill and rigor subsiding with sweating → Malaria",
                    "Fever with unconsciousness → Cerebral malaria, meningitis, encephalitis, pontine hemorrhage",
                    "Fever with neck rigidity → Meningitis, encephalitis",
                    "Fever with drenching night sweat → Lymphoma, tuberculosis",
                    "Feeling feverish with excessive sweating → Thyrotoxicosis",
                    "Pel-Ebstein (undulant) fever → Hodgkin's lymphoma",
                    "Fever with double/triple rise → Kala-azar",
                    "Step ladder pattern → Enteric fever",
                    "Relapsing fever → Malaria, borreliosis, occasionally lymphoma",
                    "Fever with myalgia → Viral infection (influenza, dengue)",
                    "Rash day 1 → Varicella; day 2 → Scarlet fever; day 3 → Pox; day 4 → Measles/Rubella; day 5 → Typhus; day 6 → Dengue; day 7 → Enteric fever (rose spot)",
                    "Hectic fever (sudden high temp with chill/rigor, falls with sweating) → Lung abscess, pyogenic liver abscess, empyema, subphrenic abscess, septicemia",
                    "Fever with relative bradycardia → Viral fever, 1st week enteric fever, brucellosis, psittacosis, Weil's disease",
                    "Fever with relative tachycardia → Acute rheumatic carditis, diphtheric myocarditis, severe TB, polyarteritis nodosa",
                    "Hyperpyrexia + rigidity on antipsychotics → Neuroleptic malignant syndrome",
                    "Aseptic fever (no infection) → SLE, lymphoma, leukemia, drug fever, AMI, heat stroke, thyrotoxic crisis, acute gout"
                ]
            },
            "Abdominal Pain": {
                icon: "🫃",
                questions: [
                    "Site: What is the site of pain?",
                    "Onset: Is it sudden or chronic? Does it disturb sleep at late night?",
                    "Character: What is the character of pain? (dull ache, colicky, stabbing, burning)",
                    "Radiation: Does it radiate to any site? (back → pancreatitis; loin to groin → renal colic; right shoulder → cholecystitis)",
                    "Association: Is it associated with diarrhea, vomiting, dyspepsia, altered bowel habit, urinary complaints, distension?",
                    "Timing and duration: How long? When does it start and go? Has it changed since beginning?",
                    "Exacerbating factors: What brings it on? What makes it worse? Is it related to meal?",
                    "Relieving factors: What makes it better?",
                    "Severity: How severe is it?"
                ],
                causes: [
                    "Epigastric pain → Peptic ulcer, acute pancreatitis, GERD, cholecystitis (also referred AMI, basal pneumonia)",
                    "Right iliac fossa pain → Acute appendicitis, Crohn's disease, salpingitis",
                    "Pain shifts from mid-abdomen to RIF → Acute appendicitis",
                    "Left iliac fossa pain → Diverticulitis, volvulus, salpingitis, IBS",
                    "Right hypochondriac pain → Acute cholecystitis, liver abscess, acute viral hepatitis, CCF, subphrenic abscess",
                    "Right hypochondriac colicky pain + jaundice → Gallstone in common bile duct",
                    "Loin pain → Renal colic, acute pyelonephritis, perinephric abscess",
                    "Generalized pain → Peritonitis, IBD, gastroenteritis",
                    "Acute pain → Acute cholecystitis, appendicitis, pancreatitis, intestinal obstruction, perforation",
                    "Chronic pain → Peptic ulcer disease, IBS (PUD may cause late night pain)",
                    "Burning pain → Peptic ulcer disease",
                    "Colicky pain → Intestinal obstruction, ureteric stone, stone in CBD, ascariasis",
                    "Pain aggravated by smoking, alcohol, NSAIDs, relieved by antacids → PUD (duodenal: worse on empty stomach, relieved by food; gastric: worse after food)",
                    "Pain aggravated by heavy meal and alcohol, partially improved by bending forward → Acute pancreatitis",
                    "Pain aggravated by fatty food → Cholelithiasis",
                    "Pain aggravated by eating → Ischemic gut",
                    "Pain aggravated by movement → Peritonitis",
                    "Pain relieved by vomiting → Gastric outlet obstruction",
                    "Pain radiating to back → Acute pancreatitis, penetrating peptic ulcer",
                    "Pain radiating loin to groin → Renal colic",
                    "Pain referred to right shoulder → Acute cholecystitis, diaphragmatic pleurisy",
                    "Pain referred to left shoulder → Splenic infarction, perisplenitis"
                ]
            },
            "Chest Pain": {
                icon: "💔",
                questions: [
                    "Site: Where is your pain? (central or peripheral part of the chest)",
                    "Onset: How did the pain start? (sudden or gradual)",
                    "Character: What is the nature of pain? (compressive, sharp, tearing, stabbing, crushing)",
                    "Radiation: Does the pain radiate to any site? (left arm, neck, jaw → IHD; between shoulder blades → dissecting aneurysm)",
                    "Timing (duration): How long does it persist? (<30 min → angina; >30 min → MI)",
                    "Exacerbating factors: What causes the pain? What makes it worse? (exertion, emotion, eating, lying flat, breathing)",
                    "Relieving factor: How is the pain relieved? (rest/GTN → angina; leaning forward → pericarditis/pancreatitis)"
                ],
                causes: [
                    "Central/retrosternal pain → AMI, angina, pericarditis, myocarditis, dissecting aorta, spontaneous pneumothorax, PE, reflux esophagitis, Mallory-Weiss, mediastinitis, tracheitis",
                    "Peripheral chest pain → Pleurisy, pneumonia, pneumothorax, pulmonary infarction, rib/chest wall (fracture, secondaries), costochondritis, herpes zoster, Bornholm disease",
                    "Pain radiating to inner left arm, neck, jaw → IHD",
                    "Compressing/crushing/squeezing/stabbing → Acute myocardial infarction",
                    "Sharp stabbing pain → Pleurisy or pericarditis",
                    "Burning pain → GERD",
                    "Very severe tearing pain (sudden onset, radiates to back) → Dissecting aortic aneurysm",
                    "Sudden onset → AMI, spontaneous pneumothorax, pulmonary embolism",
                    "Nocturnal chest pain → Heart failure, coronary artery spasm",
                    "Pain <30 minutes → Angina pectoris",
                    "Pain >30 minutes → Acute myocardial infarction",
                    "Long duration (weeks/months) → Musculoskeletal, GIT disorder, cancer",
                    "Pain on exertion/eating/emotion (3E), relieved by rest/GTN → Angina pectoris",
                    "Pain after eating, lying flat, hot drinks, alcohol → Esophageal spasm or GERD",
                    "Unilateral sharp pain aggravated by deep breathing/cough/posture → Pleuritic chest pain",
                    "Pain relieved by food → Duodenal ulcer",
                    "Pain relieved by sitting up and leaning forward → Pericarditis",
                    "Pain with breathlessness → IHD, PE, pleurisy, anxiety",
                    "Pain with nausea/vomiting/sweating → Acute MI",
                    "Pain with difficulty swallowing → Esophagitis, esophageal carcinoma",
                    "Sudden sharp chest pain + severe dyspnea → Spontaneous pneumothorax",
                    "Retrosternal pain + repeated coughing → Tracheobronchitis"
                ]
            },
            "Cough": {
                icon: "😮‍💨",
                questions: [
                    "How long have you been suffering from cough?",
                    "Is it paroxysmal or persistent?",
                    "Is it dry or productive?",
                    "If productive: amount, color, odor, time of production (morning), presence of blood, relation to posture change?",
                    "Is it associated with hemoptysis? Fresh or altered blood?",
                    "Is it associated with chest pain or dyspnea?",
                    "Is the cough aggravated by dust, cold air, smoke or pollen?",
                    "Does it occur after eating or drinking?",
                    "When does the cough get worse? (day or night)",
                    "What is the character of cough? (croupy, barking, brassy, bovine, whooping)",
                    "Are you taking any drugs? (such as ACE inhibitor)"
                ],
                causes: [
                    "Recent/acute onset → Respiratory infection, pneumonia, acute bronchitis",
                    "Chronic cough → COPD, bronchial asthma, bronchiectasis, ILD, tuberculosis",
                    "Occasional/paroxysmal → Bronchial asthma",
                    "Dry cough → ACE inhibitor (captopril/lisinopril), cough variant asthma, ILD, acute tracheobronchitis, tropical eosinophilia",
                    "Nocturnal cough → Bronchial asthma, LVF, tropical eosinophilia, post-nasal drip, aspiration",
                    "Cough with postural variation → Bronchiectasis, lung abscess, GERD",
                    "Painful cough / retrosternal pain → Tracheitis",
                    "Cough after eating/drinking → Esophageal reflux, TE fistula",
                    "Croupy cough → Laryngitis (in children exclude diphtheria)",
                    "Harsh, barking, painful + stridor → Laryngeal disorder (laryngitis, tumor)",
                    "Barking cough → Acute epiglottitis",
                    "Loud, brassy cough → Pressure on trachea by tumor",
                    "Hollow, bovine cough → Recurrent laryngeal nerve palsy (bronchial carcinoma)",
                    "Associated with whoop → Whooping cough",
                    "Cough with wheeze → Bronchial asthma, COPD",
                    "Profuse expectoration → Bronchiectasis, lung abscess, resolution stage of pneumonia",
                    "Yellowish/greenish/purulent sputum → Bronchiectasis, resolution of pneumonia",
                    "Foul smelling dark sputum → Lung abscess (anaerobic infection)",
                    "Rusty sputum → Pneumococcal pneumonia",
                    "Frothy sputum → Pulmonary edema",
                    "Hemoptysis: Respiratory → Bronchial carcinoma, TB, pulmonary infarction, bronchiectasis; Cardiac → Mitral stenosis; Blood dyscrasias → Hemophilia, DIC, anticoagulants"
                ]
            },
            "Dyspnea (Breathlessness)": {
                icon: "💨",
                questions: [
                    "Is the onset sudden (acute) or gradual (chronic)?",
                    "Does it occur with exertion or at rest?",
                    "If exertional: how much activity causes breathlessness? (mild/moderate/severe — ask about walking distance, stair climbing, undressing)",
                    "Do you have diseases such as rhinitis, asthma, heart disease, renal disorder?",
                    "Do you get breathless at night waking you from sleep? (PND) How do you feel better?",
                    "Do you feel breathless on lying flat? (orthopnea) How many pillows do you use?",
                    "Is it paroxysmal or progressive?",
                    "Is there any seasonal variation?",
                    "Any history of recent travel abroad by air?",
                    "Do you smoke? If yes, number of sticks per day.",
                    "Any aggravating factor or occupational exposure to coal dust, silica, asbestos, animal dander?",
                    "Any relieving factor? (drugs, rest, change of posture, after expectoration)",
                    "Is it associated with other symptoms? (cough, chest pain, wheeze, hemoptysis)"
                ],
                causes: [
                    "Acute/sudden dyspnea → Acute severe asthma, acute LVF, acute COPD exacerbation, spontaneous pneumothorax, PE, ARDS, cardiac tamponade, acute laryngeal obstruction, DKA, conversion disorder",
                    "Chronic dyspnea → Chronic bronchial asthma, COPD, DPLD",
                    "Dyspnea on mild exertion → COPD, LVF",
                    "Orthopnea or PND → Pulmonary edema (LVF, mitral stenosis)",
                    "Dyspnea at rest → Acute severe asthma, massive pneumothorax, ARDS, acute laryngeal edema, ILD (advanced), massive PE, acute LVF, metabolic acidosis (DKA, lactic acidosis, salicylate poisoning, acute renal failure)",
                    "Progressively increasing dyspnea → DPLD",
                    "Dyspnea with seasonal variation → Bronchial asthma, chronic bronchitis",
                    "Dyspnea after air travel/immobilization → PE from DVT",
                    "Dyspnea aggravated by coal dust/silica/asbestos/animal dander → Occupational asthma",
                    "Dyspnea with wheezing → Acute severe asthma, COPD, sometimes acute LVF, anaphylaxis",
                    "Dyspnea with stridor (upper airway obstruction) → Foreign body/tumor, acute epiglottitis, anaphylaxis, laryngeal trauma",
                    "Dyspnea with crepitations → Acute LVF (pulmonary edema), bilateral extensive bronchiectasis",
                    "Dyspnea but chest is clear → PE, metabolic acidosis (DKA, renal failure), severe anemia, shock, PCP, psychogenic",
                    "Dyspnea with unilateral chest pain → Spontaneous pneumothorax",
                    "Dyspnea with shock → Acute myocardial infarction",
                    "Dyspnea with high fever → Pneumonia",
                    "Psychogenic dyspnea → 'Inability to take a breath big enough to fill lungs'; breathing deep and punctuated with sighs"
                ]
            },
            "Vomiting": {
                icon: "🤢",
                questions: [
                    "How long have you been suffering from vomiting?",
                    "How many times do you vomit a day?",
                    "What are the contents of the vomitus?",
                    "Does it contain blood (hematemesis)?",
                    "What is the color of vomitus? (coffee ground → gastric bleeding; bile-stained green → distal pylorus obstruction)",
                    "Is it associated with nausea?",
                    "Does it occur in the morning only?",
                    "Do you induce vomiting?",
                    "Is the vomiting projectile in nature? (→ gastric outlet obstruction, raised ICP)",
                    "Does vomiting relieve abdominal pain or discomfort?",
                    "Is there any relation to food?",
                    "Any history of head injury?",
                    "Are you taking any drugs? Did you take radiation therapy?",
                    "In female: ask about amenorrhea.",
                    "Is it associated with chest pain, headache, tinnitus, vertigo, fever, jaundice, diarrhea, weight loss?"
                ],
                causes: [
                    "Food of previous day (not bile-stained) → Pyloric stenosis",
                    "Bile-stained contents → Obstruction distal to pylorus",
                    "Fecal vomiting → Distal small bowel obstruction, colonic obstruction, gastrocolic fistula",
                    "Blood in vomitus → Bleeding gastric ulcer, gastric erosion, carcinoma stomach, ruptured esophageal varices",
                    "Coffee ground vomitus → Gastric bleeding (hemoglobin → acid hematin)",
                    "Early morning vomiting (before eating) → Raised ICP, pregnancy, alcoholism",
                    "Vomiting 1 hour after food → Gastric outlet obstruction",
                    "Vomiting immediately after eating → Psychogenic, peptic ulcer with pyloric spasm",
                    "Vomiting without nausea → Raised ICP",
                    "Projectile vomiting → Gastric outlet obstruction",
                    "Induced vomiting → Gastric outlet obstruction, bulimia nervosa",
                    "Pain abdomen relieved by vomiting → Gastric outlet obstruction, gastric ulcer",
                    "Vomiting + severe abdominal pain + absolute constipation → Intestinal obstruction",
                    "Acute vomiting + diarrhea + fever → Infective gastroenteritis",
                    "Vomiting with severe abdominal pain → Renal or biliary colic",
                    "Vomiting with jaundice → Acute viral hepatitis",
                    "Vomiting with chest pain → Acute MI",
                    "Vomiting with unilateral headache → Migraine, cluster headache",
                    "Vomiting with tinnitus/vertigo → Vestibular involvement",
                    "Prolonged vomiting with little/no weight loss → Psychogenic",
                    "Non-GI causes (mnemonic ABCDEFGHIP): Acute renal failure/Addison's, Brain disease (raised ICP)/Brainstem, Cardiac (AMI), DKA, Ear disease, Foreign substance (alcohol/drugs), Gravidity, Hypercalcemia, Infection (meningitis/encephalitis), Psychogenic"
                ]
            },
            "Palpitation": {
                icon: "💓",
                questions: [
                    "What do you really feel? (unexpected awareness of heartbeat)",
                    "Did you check your pulse by yourself?",
                    "How does it start? (spontaneous or with activity, anxiety, emotion)",
                    "Is it paroxysmal or persistent?",
                    "How long does it persist?",
                    "How is it relieved?",
                    "Have you ever missed a heartbeat?",
                    "Do you get breathlessness, chest pain, dizziness or blackout with palpitation?"
                ],
                causes: [
                    "Sudden onset and termination of rapid regular palpitation → Paroxysmal SVT, atrial flutter with 2:1 block",
                    "Persistent palpitation → Anxiety neurosis, thyrotoxicosis, pregnancy",
                    "Missed beat followed by a heavy beat → Premature atrial or ventricular contractions",
                    "Rapid palpitation followed by syncope → Ventricular tachycardia",
                    "Rapid irregular palpitation → Atrial fibrillation or flutter with variable block",
                    "Rapid regular palpitation → Paroxysmal SVT",
                    "Slow palpitation → Beta blocker, pulsus bigeminus",
                    "Other causes → Heart failure, ventricular tachycardia, AF, atrial flutter"
                ]
            },
            "Jaundice": {
                icon: "🟡",
                questions: [
                    "Did it start with anorexia, nausea and vomiting? (→ acute viral hepatitis)",
                    "Any history of contact with jaundiced patient or sexual exposure?",
                    "What is the color of the stool? (yellowish, pale, dark)",
                    "Do you have itching? (→ obstructive jaundice)",
                    "Did you ever take any injection, infusion or blood transfusion? (HBV/HCV)",
                    "Any history of IV drug abuse, tattooing or surgery?",
                    "Do you take alcohol or any drugs? (hepatotoxic drugs)",
                    "Any family history of jaundice? Any consanguinity?",
                    "Did you suffer from recurrent jaundice?",
                    "Any associated history of high fever or urinary complaints?",
                    "Previous history of jaundice associated with neurological abnormality? (Wilson's disease)",
                    "Have you traveled abroad?"
                ],
                causes: [
                    "Anorexia, nausea, vomiting → Acute viral hepatitis (also drug-induced hepatitis)",
                    "Itching + pale/dark stool → Obstructive jaundice",
                    "Long-standing jaundice + itching + skin pigmentation → Primary biliary cirrhosis",
                    "History of injection/transfusion/IV drug abuse/tattooing/homosexuality → HBV or HCV",
                    "Family history of jaundice + consanguinity + pallor → Hereditary hemolytic anemia",
                    "Persistent mild jaundice → Gilbert's syndrome",
                    "Jaundice + high fever + urinary complaint → Leptospirosis",
                    "Recurrent jaundice + neurological abnormality → Wilson's disease",
                    "Jaundice with pregnancy → Cholestatic jaundice of pregnancy",
                    "Painless progressive jaundice + palpable gallbladder → Carcinoma head of pancreas",
                    "Abdominal pain + fluctuating jaundice → Bile duct stone or stricture, pancreatitis"
                ]
            },
            "Headache": {
                icon: "🤕",
                questions: [
                    "What is the site of headache? (unilateral or diffuse, frontal, occipital or facial)",
                    "What is the time of onset?",
                    "How severe is it?",
                    "What is the nature of headache? (throbbing, tight band-like, thunderclap, lancinating)",
                    "How does it start?",
                    "How long does it persist?",
                    "Is it recurrent?",
                    "Any aggravating factor such as coughing, straining or change of posture?",
                    "Any relieving factor?",
                    "Is it preceded by any aura? (zigzag lines, flashing lights → migraine)",
                    "Is it associated with fever, vomiting, weakness, blurring of vision, vertigo, nasal stuffiness, lacrimation?",
                    "Are you taking any drugs?",
                    "Where have you been? (malaria endemic area)",
                    "In female: ask about pregnancy (pre-eclampsia if proteinuria and high BP)"
                ],
                causes: [
                    "Unilateral headache preceded by flushing lights / zigzag lines → Migraine",
                    "Headache over occiput + neck stiffness → Cervical spondylosis",
                    "Generalized, worse in morning + drowsiness + vomiting → Raised ICP",
                    "Generalized + fever + photophobia + neck stiffness → Meningitis",
                    "Persistent unilateral temporal area + temporal tenderness + blurring → Temporal arteritis",
                    "Pain on forehead, cheeks or behind the eyes → Acute sinusitis",
                    "Bilateral extending to top of head / unilateral radiating to neck → Tension headache",
                    "Unilateral radiating to throat/ear/eye/nose/cheeks/face → Neuralgia",
                    "Morning headache + vomiting → Raised ICP",
                    "Sudden dramatic onset + neck stiffness → Subarachnoid hemorrhage",
                    "Persistent for days or weeks → Tension headache",
                    "Throbbing → Migraine, cluster headache",
                    "Tight band-like / pressure → Tension headache",
                    "Thunderclap (like struck by hammer) → Subarachnoid hemorrhage",
                    "Lancinating, paroxysmal → Trigeminal neuralgia",
                    "Severe pain waking from sleep in early morning → Cluster headache, raised ICP",
                    "Pain precipitated by facial movement (eating, shaving, brushing teeth) → Trigeminal/glossopharyngeal neuralgia",
                    "Pain in jaw during chewing → Temporal arteritis",
                    "Headache at onset of menarche/premenstrually → Migraine",
                    "Headache + temporary visual loss / scintillating spots → Migraine",
                    "Headache + nasal stuffiness / lacrimation → Cluster headache",
                    "Headache + fever + incoherent talk → Cerebral malaria",
                    "Chronic daily headache → Cervical spondylosis, migraine, tension headache, nitrates",
                    "Red flags: First and worst headache → SAH; Thunderclap → SAH; With fever/neck stiffness → Meningitis; Cough-induced → Raised ICP"
                ]
            },
            "Joint Pain": {
                icon: "🦵",
                questions: [
                    "Onset: Is it acute, gradual or chronic? New or recurrent?",
                    "Any history of trauma?",
                    "How long are you suffering from joint pain?",
                    "Is it associated with joint swelling?",
                    "Which joints have been involved? Number (mono/oligo/poly), symmetrical or asymmetrical, distribution (small/large)?",
                    "Does the pain move from one joint to other? (migratory or additive)",
                    "Does the pain worsen on activity or rest?",
                    "Is there any morning stiffness? How long does it persist? (>1 hr → inflammatory)",
                    "Is it associated with redness, warmth and swelling? (suggest inflammation)",
                    "Is there any deformity?",
                    "Any extra-articular manifestations? (skin, eye, mouth)",
                    "Is this associated with dry mouth? (Sjogren syndrome)",
                    "Any skin or nail problem or family history of such problem? (psoriatic arthritis)",
                    "Is the arthritis preceded by urethritis, sexual contact, acute diarrhea? (Reiter's syndrome)",
                    "Any history of frequent diarrhea? (IBD)",
                    "Any history of tick bite in endemic area? (Lyme disease)"
                ],
                causes: [
                    "Monoarticular (GRASP TH) → Gout/gonococcal, Reactive arthritis, Septic arthritis, Pseudogout/psoriatic, Tubercular, Traumatic, Hemophilic",
                    "Polyarthritis → Rheumatic fever, RA, Seronegative arthritis, OA (nodal), SLE, Gout/pseudogout, Polymyalgia rheumatica",
                    "DIP joint involved → OA, psoriatic arthritis, gout",
                    "PIP + MCP joint involved → Rheumatoid arthritis",
                    "1st MTP joint → Gout",
                    "Sacroiliac joint → Ankylosing spondylitis",
                    "Bilateral symmetrical joint → RA",
                    "Asymmetrical (larger joints) → Seronegative arthritis",
                    "Pain increased with activity, relieved by rest → Mechanical arthritis (OA)",
                    "Pain worse with rest, improved by activity → Inflammatory arthritis",
                    "Morning stiffness >1 hour, relieved by activity → RA",
                    "Fleeting arthritis → Rheumatic fever, gonococcal, SLE, Lyme, drug reaction",
                    "Deforming polyarthritis → RA, seronegative spondyloarthropathy, chronic tophaceous gout, primary generalized OA, Lyme disease",
                    "Skin rash + oral ulcer → SLE",
                    "Heliotrope rash + muscle weakness → Dermatomyositis",
                    "Triad of urethritis + iritis + arthritis → Reiter's syndrome",
                    "Psoriasis + arthritis → Psoriatic arthritis",
                    "Bowel symptoms → Enteropathic arthritis (Crohn's, UC)",
                    "Dryness of mouth and eyes → Sjogren's syndrome",
                    "Oral + genital ulcers + uveitis + skin lesion → Behcet's syndrome",
                    "History of tick bite → Lyme disease",
                    "Note: In rheumatic fever — 'it licks the joint, kills the heart' (no deformity)"
                ]
            },
            "Dysphagia": {
                icon: "🍽️",
                questions: [
                    "Can you show me with your finger at which level the food gets stuck?",
                    "Is it due to solid, liquid or both? (solid → mechanical; liquid → neurogenic; both → motility disorder)",
                    "Is it painful or painless? (painful → esophagitis/carcinoma; painless → carcinoma/achalasia)",
                    "Is it transient, intermittent or progressive? (progressive → carcinoma/achalasia/stricture)",
                    "Do you have nasal regurgitation or cough during swallowing?",
                    "Is it associated with heartburn or chest discomfort?",
                    "Did you notice bulging of the neck while eating or drinking? (→ pharyngeal pouch)"
                ],
                causes: [
                    "Difficulty with solid more than liquid → Mechanical cause (esophageal stricture, tumor, pharyngeal web, esophagitis, dysmotility, extrinsic compression by goiter/LA in MS/aortic aneurysm/posterior mediastinal mass)",
                    "Difficulty with liquid more than solid → Neurogenic cause (bulbar/pseudobulbar palsy); associated with nasal regurgitation, choking, spluttering",
                    "Difficulty with both solid and liquid → Motility disorder (achalasia, diffuse esophageal spasm, pharyngeal causes, carcinoma esophagus, stricture)",
                    "Painful dysphagia (odynophagia) → Esophagitis (herpes/candida), drug-induced, ulceration, esophageal carcinoma, achalasia",
                    "Painless dysphagia → Carcinoma esophagus, achalasia, stricture",
                    "Lower retrosternal obstruction → Carcinoma esophagus, achalasia, stricture",
                    "Obstruction at cricoid level → Tumor, stricture, pharyngeal pouch",
                    "Transient dysphagia → Esophageal infection",
                    "Progressive dysphagia → Carcinoma, achalasia, stricture",
                    "Intermittent (first few swallows only) → Esophageal spasm or esophageal ring",
                    "Dysphagia + nasal regurgitation / dysphonia / choking → Bulbar/pseudobulbar palsy, left RLN palsy (Ortner syndrome in MS)",
                    "Dysphagia + chest discomfort + heartburn → Hiatus hernia, GERD, diffuse esophageal spasm",
                    "Dysphagia + nocturnal cough / dyspnea → GERD, achalasia",
                    "Neck bulge or gurgle during drinking → Pharyngeal pouch",
                    "Dysphagia + anemia + koilonychia → Plummer-Vinson syndrome (iron deficiency anemia)",
                    "Dysphagia + palmar hyperkeratosis → Tylosis"
                ]
            },
            "Muscular Weakness": {
                icon: "💪",
                questions: [
                    "Is it generalized or localized?",
                    "Distribution: is it proximal or distal? (proximal → myopathy; distal → neuropathy)",
                    "Onset: is it sudden or gradual?",
                    "Progression: Is it ascending or descending?",
                    "Does it worsen or improve with activity? (worsens → myasthenia gravis; improves → Eaton-Lambert)",
                    "Is there other features such as muscle pain, skin rash, sensory loss, loss of bowel/bladder control?",
                    "Do you take any drug or alcohol?"
                ],
                causes: [
                    "Generalized weakness → Hypokalemia, hyperkalemia, malnutrition, chronic illness",
                    "Localized weakness → Usually neurological (hemiplegia, paraplegia, monoplegia)",
                    "Proximal weakness → All myopathies (dermatomyositis/polymyositis, myasthenia gravis, Eaton-Lambert, Cushing's, diabetic amyotrophy, thyrotoxicosis/hypothyroidism, polymyalgia rheumatica, osteomalacia, hyperparathyroidism, periodic paralysis, alcohol, McArdle's syndrome)",
                    "Distal weakness → Peripheral neuropathy, myotonia dystrophica, Charcot-Marie-Tooth disease",
                    "Sudden generalized weakness → Hypokalemic periodic paralysis, thyrotoxic periodic paralysis",
                    "Sudden localized weakness → Stroke (hemiparesis), spinal cord compression (paraparesis)",
                    "Weakness progressing hours to days → GBS, spinal cord lesion",
                    "Gradual slowly progressive → Peripheral neuropathy, spinal cord lesion, MND, myasthenia gravis, myopathy",
                    "Weakness worsens with activity → Myasthenia gravis",
                    "Weakness improves with activity → Eaton-Lambert syndrome",
                    "Weakness worsens in heat (hot bath) → Multiple sclerosis",
                    "Sudden ascending paralysis → GBS",
                    "Weakness + skin rash → Dermatomyositis",
                    "Weakness + muscle pain → Polymyalgia rheumatica, polymyositis/dermatomyositis, hypothyroidism, diabetic myopathy, hypoparathyroidism",
                    "Fasciculation present → Anterior horn cell or root lesion (motor neuron disease)",
                    "Drugs causing weakness → Statins, steroids, chloroquine, zidovudine, vincristine, alcohol, cocaine",
                    "Weakness with preserved reflex → Myotonia dystrophica, myasthenia",
                    "Weakness with loss of reflex → Neuropathy, myopathy, LMN lesion",
                    "Weakness with exaggerated reflex → UMN lesion (MND, amyotrophic lateral sclerosis)"
                ]
            },
            "Weight Loss": {
                icon: "⚖️",
                questions: [
                    "How much weight did you lose? Over what period?",
                    "How is your appetite? (good appetite + weight loss → thyrotoxicosis/DM; poor appetite → malignancy/CKD/TB)",
                    "How is your bowel habit? (frequent diarrhea/loose motion — color, amount, blood?)",
                    "Do you feel excessively thirsty and micturate frequently? (→ DM)",
                    "Do you have other symptoms such as cough, fever, night sweats? (→ TB)",
                    "Do you have palpitation? (→ thyrotoxicosis)",
                    "Do you prefer hot or cold environment?",
                    "Do you feel that you are getting darker than before? (→ Addison's disease)",
                    "Do you have vomiting? Spontaneous or induced?",
                    "Do you take alcohol or any other substance?"
                ],
                causes: [
                    "Weight loss + low grade evening fever + cough + night sweats → Tuberculosis",
                    "Weight loss despite good appetite / high food intake → Thyrotoxicosis, diabetes mellitus (also malabsorption, bulimia)",
                    "Weight loss + heat intolerance + diarrhea + palpitation → Thyrotoxicosis",
                    "Weight loss + polyphagia + polyuria + polydipsia (3P) → Diabetes mellitus",
                    "Weight loss + diarrhea/steatorrhea → Malabsorption syndrome",
                    "Weight loss + pigmentation + hypotension → Addison's disease",
                    "Extreme cachexia + young female + diet control + heavy exercise + induced vomiting + amenorrhea → Anorexia nervosa",
                    "Any malignancy, chronic illness (cardiac/pulmonary/renal failure), malnutrition → Weight loss",
                    "HIV infection should always be ruled out",
                    "Significant weight loss = reduction of 5% body weight or 5 kg within 6 months"
                ]
            },
            "Weight Gain": {
                icon: "📈",
                questions: [
                    "How much weight did you gain? Over what period?",
                    "How is your appetite? (loss of appetite + gain → hypothyroidism; increased → Cushing's/hypothalamic)",
                    "Do you feel weak or fatigue?",
                    "How is your bowel habit? (constipation → hypothyroidism)",
                    "Do you prefer hot or cold environment?",
                    "Do you take any drugs or alcohol? (steroids, TCA, sulfonylurea, beta-blockers, OCP)",
                    "How is your menstrual cycle? Any growth of excessive hair? (for females — PCOS)",
                    "Do you have headache? (→ pituitary cause)"
                ],
                causes: [
                    "Weight gain + loss of appetite → Hypothyroidism (also cold intolerance, fatigue, constipation)",
                    "Weight gain + increased appetite → Cushing's syndrome, hypoglycemia (insulinoma), hypothalamic disease",
                    "Weight gain + central obesity + moon face + plethora + hypertension + easy bruising → Cushing's syndrome (most common cause: prolonged steroid use)",
                    "Young obese female + irregular cycle/amenorrhea + hirsutism → PCOS",
                    "Headache + weight gain → Pituitary cause",
                    "Weight gain + more food intake, no other complaint → Simple obesity (may be familial)",
                    "Drugs causing weight gain → Corticosteroids, TCA, sulfonylurea, beta blockers, estrogen-containing OCP",
                    "Congenital: Prader-Willi, Laurence-Moon-Biedl, Klinefelter, Kallman, Noonan syndrome"
                ]
            },
            "Vertigo / Dizziness": {
                icon: "🌀",
                questions: [
                    "What exactly do you feel? Spinning, light-headedness, fainting or unsteadiness?",
                    "Is it constant or episodic?",
                    "How long does each episode last?",
                    "Is it associated with nausea or vomiting?",
                    "Is it associated with ear symptoms? (tinnitus, hearing loss → Meniere's disease or labyrinthitis)",
                    "Is it positional? Does it occur on turning your head?",
                    "Is it associated with double vision, weakness or numbness? (→ central cause)",
                    "Did you have any recent head injury?",
                    "Are you taking any drugs? (aminoglycosides, loop diuretics, aspirin)"
                ],
                causes: [
                    "Acute or sudden vertigo → Vestibular neuronitis, labyrinthitis, multiple sclerosis, skull fracture, Meniere's disease, CVD involving brainstem/cerebellum",
                    "Recurrent vertigo <1 minute → Benign positional vertigo, post-traumatic vertigo, psychogenic",
                    "Recurrent vertigo minutes to hours → Migraine, vertebrobasilar insufficiency, Meniere's disease",
                    "Spontaneous prolonged vertigo (a day or more) → Labyrinthitis, multiple sclerosis, brainstem infarction",
                    "Vertigo + hearing loss + tinnitus → Peripheral disorder (Meniere's disease, labyrinthitis; also ototoxic drugs like aminoglycosides)",
                    "Vertigo + neurological disorders / chronic without cochlear symptoms → Central lesion (brainstem, cerebellum, CP angle)",
                    "Vertigo precipitated by head movement in specific direction → Benign positional vertigo",
                    "Vertigo + slowly progressive unilateral hearing loss + tinnitus + disequilibrium → Acoustic neuroma",
                    "Intermittent brief vertigo + drop attack + ataxia + visual loss + double vision + confusion → Vertebrobasilar insufficiency",
                    "Episodic recurrent vertigo + auditory symptoms + headache + photophobia + aura → Migraine",
                    "Vertigo + facial weakness + loss of taste sensation → Ramsay Hunt syndrome",
                    "Triad of episodic vertigo + tinnitus + progressive deafness → Meniere's disease",
                    "Psychogenic vertigo → Associated with agoraphobia; no nystagmus; patient still attempts to work despite discomfort",
                    "Central vertigo → Chronic, mild, bidirectional; vertical nystagmus (up/down beat) is pathognomonic",
                    "Peripheral vertigo → Sudden, severe, unilateral, brief; unidirectional nystagmus; often with unilateral deafness/tinnitus"
                ]
            },
            "Body Swelling / Edema": {
                icon: "🦶",
                questions: [
                    "Where did the swelling start? (face/periorbital → renal; feet ascending upwards → cardiac)",
                    "Is it pitting or non-pitting?",
                    "Is it unilateral or bilateral?",
                    "How long have you had the swelling?",
                    "Is it associated with breathlessness, oliguria or abdominal swelling?",
                    "Do you have any history of renal, cardiac or liver disease?",
                    "Is there any itching or change in skin color with the swelling?",
                    "Are you taking any drugs? (nifedipine, amlodipine → pedal edema)"
                ],
                causes: [
                    "Periorbital puffiness in morning + oliguria → Renal cause (GN or nephrotic syndrome); if preceded by skin/throat infection + smoky urine → Post-streptococcal GN",
                    "Generalized swelling + anemia + hypertension → CRF",
                    "Swelling starts at legs, ascends upwards + exertional dyspnea → Cardiac cause (CCF)",
                    "Gradual whole body swelling + non-pitting + cold intolerance + lethargy → Hypothyroidism",
                    "Generalized swelling → Also wet beriberi, cyclical edema",
                    "Swelling + steatorrhea → Hypoalbuminemia due to malabsorption",
                    "Abdominal swelling (ascites) starts first → CLD (cirrhosis of liver)",
                    "Abdominal swelling + abdominal pain + anorexia + weight loss → Abdominal malignancy with peritoneal metastasis",
                    "Abdominal swelling first, then leg swelling in advanced stage → Constrictive pericarditis",
                    "Unilateral leg swelling + non-pitting edema → Lymphedema (filariasis)",
                    "Unilateral painful leg swelling sudden onset → DVT",
                    "Pitting unilateral lower limb edema → DVT, compression by tumor or lymph nodes",
                    "Non-pitting lower limb edema → Hypothyroidism, lymphedema (filariasis, malignancy, congenital, allergic, Milroy's disease)",
                    "Localized swelling → Angioedema",
                    "Unilateral painful red swelling + fever in toxic patient → Cellulitis",
                    "Gradual truncal swelling on steroid → Cushing's syndrome",
                    "Drugs: nifedipine, amlodipine → Pedal edema",
                    "Unilateral arm edema → Post surgery/removal of axillary lymph nodes (breast carcinoma)"
                ]
            },
            "Cold / Heat Intolerance": {
                icon: "🌡️",
                questions: [
                    "If cold intolerance: Do you have weight gain, lethargy, increased sleepiness, constipation? (→ hypothyroidism)",
                    "If heat intolerance or excessive sweating: Do you have increased appetite, weight loss, palpitation, diarrhea, irritability? (→ thyrotoxicosis)",
                    "Any neck swelling?",
                    "Any tremor of hands?"
                ],
                causes: [
                    "Cold intolerance → Hypothyroidism, old age, excessive environmental cold",
                    "Heat intolerance → Thyrotoxicosis, menopausal syndrome",
                    "Excess sweating (hyperhidrosis) → Anxiety neurosis, thyrotoxicosis, pheochromocytoma, acromegaly, autonomic neuropathy, excess antipyretics, fever, severe pain, menopausal syndrome, malignancy, amyloidosis, neuroleptic malignant syndrome, drugs (thyroxin, somatostatin analog, vasopressin, epinephrine)",
                    "Less/no sweating (anhidrosis) → Hypothyroidism, hypothermia, autonomic neuropathy, Sjogren's syndrome, anticholinergic drugs, vitamin A deficiency, hypoadrenalism"
                ]
            },
            "Polyuria": {
                icon: "💧",
                questions: [
                    "What is the amount of water you take and void every day? (>3L/day = polyuria)",
                    "Are you suffering from diabetes mellitus?",
                    "Is it associated with excessive thirst? (→ DM, diabetes insipidus)",
                    "Do you have excessive thirst with polyphagia? (→ DM)",
                    "Are you taking any drugs? (diuretic, lithium, analgesic)",
                    "Do you take alcohol or excessive coffee?",
                    "Do you have excess thirst, abdominal pain, constipation? (→ hypercalcemia)",
                    "Do you have history of head trauma, pituitary surgery or stroke? (→ cranial diabetes insipidus)",
                    "Any history of psychiatric illness? (→ psychogenic polydipsia)"
                ],
                causes: [
                    "Polyuria + polyphagia + polydipsia (3P) → Diabetes mellitus (also thyrotoxicosis, obesity, bulimia)",
                    "Polyuria + excessive thirst → Diabetes insipidus, anxiety, DM",
                    "History of head injury or surgery → Cranial diabetes insipidus",
                    "Polyuria + constipation + abdominal pain + excess thirst → Hypercalcemia",
                    "History of psychiatric disease → Psychogenic polydipsia",
                    "Drugs causing polyuria → Diuretics, lithium, analgesics, cidofovir, foscarnet",
                    "Other causes → DM, diabetes insipidus (cranial/nephrogenic), psychogenic polydipsia, hypercalcemia, CRF, excess water intake, alcohol, renal tubular disease, adrenal insufficiency"
                ]
            },
            "Urine": {
                icon: "🧪",
                questions: [
                    "What is the colour of your urine? Has it changed recently? (clear, dark/cola-coloured, red, cloudy)",
                    "Is your urine frothy or foamy? (→ proteinuria, nephrotic syndrome)",
                    "Do you pass urine more often than usual, including at night? (frequency, nocturia)",
                    "Do you feel a sudden, hard-to-control urge to pass urine? (urgency)",
                    "Do you leak urine involuntarily — with coughing/sneezing, or with sudden urge? (stress vs urge incontinence)",
                    "Do you have difficulty starting the urine stream, straining, poor flow, or dribbling at the end? (hesitancy, voiding symptoms)",
                    "Do you feel your bladder is not completely empty after passing urine?",
                    "Has the total amount of urine decreased markedly, or stopped completely? (oliguria/anuria)",
                    "Have you noticed gas bubbles passing in your urine? (pneumaturia)",
                    "Does your urine have an unusual or strong smell?",
                    "Are you taking any medication that could change urine colour (e.g., rifampicin) or have you eaten beetroot recently?",
                    "Do you have fever, loin pain, or burning during urination along with the urine change?"
                ],
                causes: [
                    "Dark/cola-coloured urine → Conjugated hyperbilirubinaemia (hepatic/obstructive jaundice), haemoglobinuria, myoglobinuria, rifampicin",
                    "Frothy/foamy urine → Heavy proteinuria — nephrotic syndrome, glomerulonephritis",
                    "Cloudy urine → Pyuria (leucocytes) — urinary tract infection",
                    "Red urine (non-blood causes) → Beetroot, rifampicin, some laxatives — distinguish from true haematuria",
                    "Frequency + urgency + nocturia + urge incontinence (storage symptoms) → UTI, bladder tumour, urethral calculi, BPH/prostatic obstruction, neurological disease (e.g., multiple sclerosis)",
                    "Hesitancy + poor stream + straining + terminal dribbling (voiding symptoms) → Bladder outflow obstruction — prostatic enlargement (men), urethral obstruction or genital prolapse (women)",
                    "Stress incontinence → Leakage with coughing/sneezing/increased abdominal pressure — weak pelvic floor",
                    "Urge incontinence → Sudden urge followed by involuntary leakage — overactive bladder, UTI, neurological",
                    "Overflow incontinence → Painless leakage without warning, often with position change — chronic retention",
                    "Oliguria (<500mL/day) / Anuria → Very low fluid intake, mechanical obstruction (stones, BPH), or acute/chronic kidney injury",
                    "Pneumaturia (gas in urine) → Vesicocolic fistula — diverticular abscess, colonic malignancy, inflammatory bowel disease",
                    "Strong/unusual odour → Urinary tract infection, certain foods (e.g., asparagus), uncontrolled diabetes (ketotic smell)"
                ]
            },
            "Hematuria": {
                icon: "🔴",
                questions: [
                    "Is it at the beginning of micturition, at the end or throughout? (initial → urethra; terminal → bladder/prostate; total → bladder and above)",
                    "Do you feel pain or burning during micturition? (dysuria)",
                    "Is this associated with frequency, urgency or hesitancy?",
                    "Do you have loin pain? Does it radiate to the groin?",
                    "Have you noticed bleeding from any other part of the body?",
                    "Do you have fever?",
                    "Is it associated with nausea or vomiting?",
                    "Have you noticed any rash? Is it associated with joint pain and swelling?",
                    "Do you take any drugs? (anticoagulant, antiplatelet, analgesic, cyclophosphamide)",
                    "Did you ever pass stones previously?",
                    "Did you suffer from any kind of trauma?",
                    "Did you suffer from skin infection or sore throat recently? (→ post-streptococcal GN)",
                    "Do you have hypertension, exertional breathlessness and swelling of the body?",
                    "Any family history of renal disease?",
                    "In female: enquire whether she is menstruating.",
                    "Occupational history — exposure to radiation or industrial chemicals like benzene?",
                    "Have you recently traveled to any Middle Eastern country? (bilharziasis/schistosomiasis)"
                ],
                causes: [
                    "Hematuria + dysuria → Cystitis or urethritis (UTI)",
                    "Hematuria + >trace of protein in urine → Blood of renal origin",
                    "Hematuria + loin pain + high grade fever with chill/rigor + nausea/vomiting → Acute pyelonephritis",
                    "Hematuria + fever → Also infective endocarditis with renal involvement, SLE",
                    "Hematuria + loin-to-groin pain → Renal stone (bladder stone: lower abdominal pain)",
                    "Painful hematuria → Loin pain hematuria syndrome, UTI",
                    "Painless hematuria → Tumor of kidney/ureter/bladder/prostate, renal TB, GN, schistosomiasis, bleeding disorders, BPH, IgA nephropathy, infective endocarditis, hypertensive nephrosclerosis, interstitial nephritis, drugs (heparin, anticoagulants)",
                    "Hematuria + obstructive features in elderly male → BPH or carcinoma prostate",
                    "Hematuria + previous skin/throat infection + hypertension + generalized body swelling → Acute glomerulonephritis",
                    "Drugs: analgesics (papillary necrosis), cyclophosphamide (haemorrhagic cystitis), antibiotic (interstitial nephritis), anticoagulants/antiplatelets",
                    "Hematuria + hypertension → Renovascular disease",
                    "Family history of renal disease → Polycystic kidney disease",
                    "Bleeding from multiple sources → Bleeding disorder or drug-induced",
                    "Hematuria + bruise/purpura → Coagulation disorder, HSP, vasculitis",
                    "Hematuria + abdominal pain + vasculitic rash over lower limbs → Henoch-Schonlein purpura",
                    "Young fit athlete + hematuria → Exercise-induced hematuria",
                    "Hematuria + DM or sickle cell disease → Papillary necrosis",
                    "Recent travel to Middle East → Bilharziasis (schistosomiasis) strongly suspected"
                ]
            }
        }
    }
};
